- docs/Usage-Guide.md
This pull request enhances the download instructions in the `docs/Usage-Guide.md` file to provide users with troubleshooting steps if the Android script download fails.
Added a line to the download instructions suggesting users try changing their internet connection, DNS settings, or using a VPN if the provided link for the `.sh` file download does not work.
This enhancement aims to improve the user experience by providing guidance in case of download failures.
> Android Usage Guide : Instruction for when script not getting download. 

- internal/handlers/handlers.go
Very minor update, resolves issues if your server is configured to block connections to non HTTPS hosts.
> Update image host to use https

- internal/handlers/auth.go
- internal/handlers/handlers.go
- internal/handlers/types.go
Currently, we are only refreshing `AccessToken` whenever it is expired. 
This leads to a recurring issue where the user has to logout and re-login to make the channels work again. This issue should be solved if we also refresh `SSOToken` along with `AccessToken`
> Refresh SSOToken while refreshing AuthToken

- docs/usage/linux-macos.md
This commit updates the documentation to include a guide on how to set up JioTV Go as a systemd service on Linux for autostarting the application. The guide covers the following steps:
1. Creating a service-specific user and group for enhanced security.
2. Configuring the `jiotv_go.service` file with the appropriate settings.
3. Setting up user-specific configuration for the service.
4. Enabling and starting the `jiotv_go` service.
The guide provides detailed instructions and code snippets to assist users in successfully running JioTV Go as a systemd service on their Linux systems.
> docs: Add guide for running JioTV Go as a systemd service

- .github/workflows/pre-release.yml
- Dockerfile
- cmd/jiotv_go.go
- go.mod
- go.sum
- internal/handlers/auth.go
- internal/handlers/handlers.go
- main.go
- pkg/epg/epg.go
- pkg/scheduler/scheduler.go
- pkg/store/store.go
- pkg/utils/types.go
- pkg/utils/utils.go
- Bump Go version to 1.22
- New efficient Task scheduler, that should fix uninterrupted caches and login problems
- Added few missing cache headers.
- More under the hood fixes.
> feat: Improve Scheduler, Auth and Cache (v.3.5)

- scripts/install.sh
Identified architecture after uname -m detected system as arm when it was arm64. Fixed identification args to match the identified architecture.
> Arm64 fixed install.sh

- pkg/epg/epg.go
- pkg/epg/types.go
This change adds programme.showCategory as category so that media servers can use it to categorize the shows
ShowCategory of programmes from the api:
```
Business and Finance: 828
Business News: 72
News: 37039
Sports: 432
Sport: 1774
Education: 6192
Documentary: 1503
Infotainment: 864
Play: 27
TV Show: 31076
Radio Shows: 9
Music: 7193
Entertainment: 2096
Lifestyle: 600
Kids: 672
Children: 4007
Movies: 3610
Film: 2184
Devotional: 6119
```
How it works on jellyfin:
ref: https://github.com/XMLTV/xmltv/blob/8c9d4a17e0253f758f8c863a70c1c5b0c70f3436/xmltv.dtd#L373-L378
> Save categories while generating epg

- docs/usage/iptv.md
- internal/handlers/handlers.go
Currently the playlist channels can be grouped by below two options:
- By category (default)
- Example: `Movies`, `Entertainment`, `News`, etc.
- This is the default grouping
- By category - language
- Example: `Movies - Hindi`, `Entertainment - Kannada`, `News - Telugu`, etc.
- This grouping can be done by passing `c=split` request parameter to `/playlist.m3u` URL
A new addition to the playlist channels grouping can be done via grouping by languages only. This will create groups based on language and will include all the channels from different categories of the language.
- Example: `Hindi`, `Kannada`, `Telugu`, etc.
- This grouping can be done by passing `c=language` request parameter to `/playlist.m3u` URL
- This will still work in combination of `l` parameter to filter the languages …
> Group channels by language only using c=language query parameter

- pkg/epg/epg.go
This resolves the issue with Kodi, where the EPG was not functioning properly.
> fix epg for Kodi player

- docs/usage/iptv.md
- docs/usage/paths.md
- internal/handlers/handlers.go
This PR adds query parameter to skip some genres from playlist. This is useful for filtering playlist to skip channels from specific genres.
E.g.: `&sg=Devotional,Educational,Lifestyle,Shopping`
I am using this server to add live tv channels to my Jellyfin. This is working flawlessly for last 2 weeks. Only issue I have is, there are too many channels that I dont need. This query param helps filter out some of the channels.
> feat: Add query parameter to skip specific genres from m3u playlist

- internal/handlers/auth.go
- internal/handlers/drm.go
- internal/handlers/handlers.go
- pkg/store/store.go
- pkg/television/television.go
- pkg/utils/utils.go
> Hotfix Release Sep 9 2024

- cmd/background.go
- docs/usage/usage.md
- main.go
- Added `--config` argument support to `background` commands
- Removed usage of `GetPathPrefix()` function before initializing the config file
- Fix #421
> Removed usage of GetPathPrefix function without reading the config

- cmd/jiotv_go.go
- docs/usage/usage.md
- main.go
Removed Prefork mode from the Go fiber server setup to facilitate dual stack (IPv4 and IPv6) support. This change ensures better network compatibility.
Updated relevant configurations and documentation to reflect the changes.
BREAKING CHANGE: Prefork mode has been removed, which may impact performance in a multi-core setup.
> feat(fiber): remove Prefork mode to enable dual-stack support

- internal/handlers/drm.go
- internal/handlers/handlers.go
- pkg/television/types.go
- Fixed sonyLiv channels trowing error
- You must enable DRM for few SonyLiv channels as they only provide DASH streams.
- Removed old SL redirect channel components as their deprecated
> Fix SonyLiv channels and remove old SL redirect components

- web/views/flow_player_drm.html
Set startAtSegmentBoundary and alwaysStreamFullSegments to true in the Shaka Player configuration for DRM streams.
This aims to resolve an issue where videos would buffer initially or after seeking, potentially due to playback starting or resuming at non-segment boundaries.
> Fix: Improve Shaka Player buffering for DRM streams

- pkg/utils/utils.go
This commit introduces server-side logout functionality.
The existing logout process only cleared local credentials. This change enhances it by making a POST request to the JioTV logout API (https://auth.media.jio.com/tokenservice/apis/v1/logout) to invalidate the session on the server as well.
Changes include:
- Added a new `PerformServerLogout()` function in `pkg/utils/utils.go` to handle the API call.
- Modified the existing `Logout()` function in `pkg/utils/utils.go` to call `PerformServerLogout()` before clearing local credentials.
- Ensured that local credentials are cleared regardless of the success of the server-side API call.
- No changes were required in `internal/handlers/auth.go` or `cmd/login.go` as they already utilize the updated `utils.Logout()`.
> feat: Implement server-side logout

- cmd/login.go
The panic occurred because the logger was used in `utils.GetDeviceID` before it was initialized. This happened when `store.Get("deviceId")` returned an error.
This commit fixes the issue by ensuring that the global logger `utils.Log` is initialized at the beginning of `cmd.LoginOTP` and `cmd.LoginPassword` functions before any code path that might use the logger is executed.
Fixes #501
> Fix: Prevent nil pointer dereference in OTP login flow

- internal/handlers/handlers.go
Replaces `%s` with `%q` when formatting `tvg-id` in M3U output to ensure the attribute is properly quoted.
- `tvg-id=channel123` was rendered without quotes
- Some IPTV players failed to match EPG data due to this
- Changed string formatting from `%s` to `%q` to produce `tvg-id="channel123"`
- Ran the server and generated `playlist.m3u`
- Verified correct `tvg-id="..."` format
- Confirmed proper EPG-channel linkage in IPTV player
> Fix: Properly quote tvg-id in M3U entries using %q

- internal/handlers/drm.go
- pkg/television/television.go
- pkg/television/types.go
- web/views/flow_player_drm.html
Closes #506 
- Added support for timesplay channels in getDrmMpd function.
- Updated API endpoint in Television's Live method for better URL retrieval.
- Extended LiveURLOutput struct to include extId and algoName fields.
- Improved flow_player_drm.html with buffering and low latency settings.
> feat: Enhance DRM handling and improve playback URL retrieval

- go.mod
- internal/handlers/handlers.go
- internal/utils/handlers.go
- pkg/television/television.go
- pkg/television/types.go
- pkg/television/url_utils.go
This pull request introduces comprehensive improvements to how Akamai token (`hdnea`) handling is managed throughout the live streaming and media serving pipeline. The changes ensure that the `hdnea` token is correctly extracted, propagated, and updated between upstream and downstream requests, and that it is never leaked to clients. This enhances stream reliability, especially when tokens rotate, and improves security by keeping cookies server-side only.
**Live stream and token propagation enhancements:**
* Added logic in `pkg/television/television.go` to extract the `hdnea` token from live stream URLs, append it to all relevant URLs if present, and include it in the `LiveURLOutput` struct for downstream use. [[1]](diffhunk://#diff-0f867743c99bf0c350cd630d60cd251673a4790131dbb427a48827a5c …
> Add hdnea token handling in live stream URLs and related functions
